#!/system/bin/sh

IFACE="$1"

case $IFACE in
    ppp1)
	echo 0 > /proc/sys/net/ipv4/ip_forward;
	;;
    ppp0)
	setprop "net.interfaces.defaultroute"   ""
	;;
esac

rm /etc/ppp/ppp*.pid

# Use interface name if linkname is not available
NAME=${LINKNAME:-"$IFACE"}

# Cleanup android specific variables
setprop "ril.ifname"			""
setprop "net.gprs.dns1"			""
setprop "net.gprs.dns2"			""
setprop "net.gprs.pppd_pid"		""
setprop "net.$NAME.dns1"		""
setprop "net.$NAME.dns2"		"" 
setprop "net.$NAME.local-ip"		"" 
setprop "net.$NAME.remote-ip"		"" 
setprop "net.$NAME.gw"			""
setprop "net.$IFACE.status"		""
